#!/bin/sh
# CI gate: every rule copy must contain byte-identical canonical body text.
#
# Copies are generated by gen-rule-copies.sh. If this check drifts, either a
# copy was hand-edited (forbidden: regenerate) or the canonical text changed
# without regenerating; both are fixed by running gen-rule-copies.sh.
set -eu

ROOT=$(cd "$(dirname "$0")/.." && pwd)
CANONICAL="$ROOT/plugins/memvault/rules/memvault.md"

body=$(sed -n '/memvault:canonical-begin/,/memvault:canonical-end/p' "$CANONICAL")
[ -n "$body" ] || { echo "no canonical block in $CANONICAL" >&2; exit 1; }

status=0
for copy in integrations/rules/cursor.mdc integrations/rules/clinerules.md \
    integrations/rules/kiro-steering.md integrations/rules/agents-snippet.md \
    .qoder/rules/memvault.md; do
    path="$ROOT/$copy"
    if [ ! -f "$path" ]; then
        echo "missing copy: $copy"
        status=1
        continue
    fi
    if grep -qF "$body" "$path"; then
        echo "ok - $copy in sync"
    else
        echo "out of sync: $copy (run scripts/gen-rule-copies.sh)"
        status=1
    fi
done

# Generated skill copies must stay byte-identical to the plugin source dir.
for tree in "$ROOT/skills" "$ROOT/.openclaw/skills"; do
    if diff -rq -x .DS_Store "$ROOT/plugins/memvault/skills" "$tree" >/dev/null 2>&1; then
        echo "ok - ${tree#"$ROOT/"} in sync"
    else
        echo "out of sync: ${tree#"$ROOT/"} (run scripts/gen-rule-copies.sh)"
        status=1
    fi
done
exit "$status"
